export const petals = {
  stinger: { damage: 15, health: 5, reload: 3000 },
  antennae: { damage: 0, health: 0, ability: "visionBoost" },
  stick: { damage: 5, health: 10, reload: 1000 },
  toughScale: { damage: 7, health: 50, reload: 2500 },
  scale: { damage: 5, health: 25, reload: 2000 },
  fang: { damage: 8, health: 10, reload: 1500 },
  tooth: { damage: 10, health: 10, reload: 2000 },
  fur: { healthBoost: 30, ability: "pacifyCoyoteMutt" },
  tail: { ability: "doubleDrops" },
  flesh: { damage: 10, health: 10, ability: "recoilMob", reload: 5000 },
  cloth: { healthBoost: 50 },
  poisonousFlask: {
    damage: 12,
    health: 1,
    ability: "consumeDamage",
    consumeEffect: 20,
    reload: 5000,
  },
  ygg: {
    damage: 1,
    health: 1,
    ability: "revivePlayer",
    reload: 10000,
  },
  crowEgg: {
    ability: "summonCrow",
    crowStats: { damage: 20, health: 50 },
    reload: 7000,
  },
  feather: { damage: 500, health: 1, reload: 50000 },
  pepper: {
    damage: 5,
    health: 5,
    ability: "consumeHeal",
    healAmount: 5,
    reload: 2000,
  },
  sand: { damage: 7, health: 2, reload: 1000 },
  cucumber: {
    damage: 5,
    health: 5,
    ability: "consumeHeal",
    healAmount: 10,
    reload: 2000,
  },
  strawberry: {
    damage: 2,
    health: 5,
    ability: "consumeHeal",
    healAmount: 3,
    reload: 1000,
  },
  squash: {
    damage: 5,
    health: 5,
    ability: "consumeHeal",
    healAmount: 5,
    healthBoost: 10,
    reload: 4000,
  },
  vine: { damage: 10, health: 5, reload: 1500 },
  light: { damage: 3, health: 5, ability: "rotateBoost", reload: 1500 },
};
